added files

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -64,19 +64,19 @@ jobs:
           echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
           echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
 
-      - name: Verify Secrets Loaded
-        run: |
-          echo "Checking if secrets were loaded successfully..."
-          if [ -z "$IONOS_USERNAME" ]; then
-            echo "ERROR: IONOS_USERNAME is empty"
-            exit 1
-          fi
-          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
-            echo "ERROR: AWS_ACCESS_KEY_ID is empty"
-            exit 1
-          fi
-          echo "Secrets loaded successfully!"
-        shell: bash
+      # - name: Verify Secrets Loaded
+      #   run: |
+      #     echo "Checking if secrets were loaded successfully..."
+      #     if [ -z "$IONOS_USERNAME" ]; then
+      #       echo "ERROR: IONOS_USERNAME is empty"
+      #       exit 1
+      #     fi
+      #     if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+      #       echo "ERROR: AWS_ACCESS_KEY_ID is empty"
+      #       exit 1
+      #     fi
+      #     echo "Secrets loaded successfully!"
+      #   shell: bash
 
       - name: Install Opentofu
         uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6
