added files

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -69,6 +69,8 @@ jobs:
           echo "IONOS_ENDPOINT: $IONOS_ENDPOINT"
           echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
           echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
+          echo "AWS_REGION: $AWS_REGION"
+
 
       - name: Verify Secrets Loaded
         run: |
@@ -79,6 +81,18 @@ jobs:
           fi
           if [ -z "$AWS_ACCESS_KEY_ID" ]; then
             echo "ERROR: AWS_ACCESS_KEY_ID is empty"
+            exit 1
+          fi
+          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+            echo "ERROR: AWS_SECRET_ACCESS_KEY is empty"
+            exit 1
+          fi
+          if [ -z "$IONOS_PASSWORD" ]; then
+            echo "ERROR: IONOS_PASSWORD is empty"
+            exit 1
+          fi
+          if [ -z "$IONOS_TOKEN" ]; then
+            echo "ERROR: IONOS_TOKEN is empty"
             exit 1
           fi
           echo "Secrets loaded successfully!"
@@ -94,7 +108,7 @@ jobs:
         id: fmt
         working-directory: infrastructure
         run: tofu fmt -check
-        continue-on-error: true
+        continue-on-error: false
         env:
           OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
           TF_VAR_AWS_ACCESS_KEY_ID: op://K8s/ionos/AWS_ACCESS_KEY_ID  
@@ -174,7 +188,7 @@ jobs:
         run: tofu plan -lock=false -out .planfile | grep -v "Refreshing state...\|Reading...\|Read complete after"
 
       - name: Post PR comment
-        continue-on-error: true
+        continue-on-error: false
         uses: borchero/terraform-plan-comment@434458316f8f24dd073cd2561c436cce41dc8f34 # v2.4.1
         with:
           token: ${{ secrets.TOKEN }}
