added files

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -36,24 +36,7 @@ jobs:
       - name: Install 1Password CLI
         uses: 1password/install-cli-action@f5d505685ccf986ef535da41cd180792c8ac3a36 # v2.0.1
 
-      - name: Debug - Test 1Password Connection
-        run: |
-          echo "Testing 1Password connection..."
-          echo "OP_SERVICE_ACCOUNT_TOKEN length: ${#OP_SERVICE_ACCOUNT_TOKEN}"
-          # Test if the token is valid
-          if op --version; then
-            echo "1Password CLI installed successfully"
-          else
-            echo "1Password CLI failed"
-            exit 1
-          fi
-        env:
-          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
 
-      - name: Configure 1password
-        uses: 1password/load-secrets-action@v2 # v3.0.0
-        env:
-          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
 
       - name: Get Secrets
         id: load-secrets
@@ -61,12 +44,13 @@ jobs:
         with:
           export-env: true
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          IONOS_USERNAME: ${{ secrets.IONOS_USERNAME }}
-          IONOS_PASSWORD: ${{ secrets.IONOS_PASSWORD }}
-          IONOS_TOKEN: ${{ secrets.IONOS_TOKEN }}
-          IONOS_ENDPOINT: ${{ secrets.IONOS_ENDPOINT }}
+          AWS_ACCESS_KEY_ID: op://K8s/aws/AWS_ACCESS_KEY_ID 
+          AWS_SECRET_ACCESS_KEY: op://K8s/aws/AWS_SECRET_ACCESS_KEY
+          IONOS_USERNAME: op://K8s/ionos/IONOS_USERNAME
+          IONOS_PASSWORD: op://K8s/ionos/IONOS_PASSWORD
+          IONOS_TOKEN: op://K8s/ionos/IONOS_TOKEN
+          IONOS_ENDPOINT: op://K8s/ionos/IONOS_ENDPOINT
+          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
 
       - name: Verify Secrets Loaded
         run: |
@@ -81,7 +65,19 @@ jobs:
           fi
           echo "Secrets loaded successfully!"
 
-
+          - name: Debug - Test 1Password Connection
+          run: |
+            echo "Testing 1Password connection..."
+            echo "OP_SERVICE_ACCOUNT_TOKEN length: ${#OP_SERVICE_ACCOUNT_TOKEN}"
+            # Test if the token is valid
+            if op --version; then
+              echo "1Password CLI installed successfully"
+            else
+              echo "1Password CLI failed"
+              exit 1
+            fi
+          env:
+            OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
       - name: Install Opentofu
         uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6
         with:
